package TetrisLike2DSolver;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import TetrisLike2DSolver.Pentominos2DSolverMT.Solution;

import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.zip.GZIPInputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Federico
 */
public class Main2D extends javax.swing.JFrame {

    private KeyEventDispatcher f9;

    /**
     * Creates new form Main
     */
    public Main2D() {
        initComponents();
        setMinimumSize(getSize());
        f9 = new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_F9 && e.getID() == KeyEvent.KEY_PRESSED) {
                    JFileChooser c = new JFileChooser();
                    c.setDialogTitle("Load state");
                    c.setMultiSelectionEnabled(false);
                    c.showOpenDialog(rootPane);
                    File x = c.getSelectedFile();
                    if (x == null) {
                        return false;
                    }
                    GZIPInputStream fis = null;
                    try {
                        fis = new GZIPInputStream(new FileInputStream(x));
                        setVisible(false);
                        Pentominos2DSolverMT solver = Pentominos2DSolverMT.loadState(fis);
                        rows.setValue(solver.getHeight());
                        cols.setValue(solver.getWidth());
                        l.setValue(solver.getLBlocks());
                        p.setValue(solver.getPBlocks());
                        t.setValue(solver.getTBlocks());
                        new Visualizer(solver, Main2D.this).setVisible(true);
                    } catch (Throwable t) {
                        JOptionPane.showMessageDialog(rootPane, "Invalid saved state", "Error", JOptionPane.ERROR_MESSAGE);
                        setVisible(true);
                    } finally {
                        try {
                            fis.close();
                        } catch (Throwable t) {
                        }
                    }
                }
                return false;
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rows = new javax.swing.JSpinner();
        cols = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        t = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        l = new javax.swing.JSpinner();
        p = new javax.swing.JSpinner();
        solve = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        optimization = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tetris Puzzle Solver");

        jLabel1.setText("Rows");

        jLabel2.setText("Columns");

        rows.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(5), Integer.valueOf(0), null, Integer.valueOf(1)));

        cols.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2), Integer.valueOf(1), null, Integer.valueOf(1)));


        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("l.png"))); // NOI18N
        
        l.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2), Integer.valueOf(0), null, Integer.valueOf(1)));
        
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("p.png")));
        
        p.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("t.png"))); // NOI18N

        t.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        
        

        solve.setText("Solve");
        solve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveActionPerformed(evt);
            }
        });

        jLabel10.setText("Algorithm");

        optimization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Classic", "Parallel" }));
        optimization.setSelectedIndex(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(solve, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cols)
                            .addComponent(rows)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l))
                    .addGroup(layout.createSequentialGroup()
                    		.addComponent(jLabel6)
                    		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    		.addComponent(p))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optimization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(optimization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(solve)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    private void solveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveActionPerformed
        if (optimization.getSelectedIndex() == 1) {
            new Visualizer(new Pentominos2DSolverMT((Integer) (cols.getValue()), (Integer) (rows.getValue()), (Integer) (l.getValue()), (Integer) (p.getValue()), (Integer) (t.getValue())), this).setVisible(true);
        }
        setVisible(false);
    }

    @Override
    public void setVisible(boolean visible) {
        if(isVisible()==visible) return;
        super.setVisible(visible);
        if (!visible) {
            KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventDispatcher(f9);
        } else {
            KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(f9);
        }
        System.gc();
    }

    private static void printHelp() {
        System.out.println("Tetris Puzzle Solver - Command Line Help\n"
                + "Syntax: TetrisPuzzleSolver.jar [-nogui | -gui] [-classic | -parallel] -gridRowsxCols -iN -oN -tN -jN -lN -sN -zN\n"
                + "\n"
                + "-nogui: prints output to stdout instead of showing GUI\n"
                + "-gui: shows animated GUI\n"
                + "-classic: use classic algorithm (single thread)\n"
                + "-parallel: use parallel algorithm\n"
                + "-gridRowsxCols: specifies board size\n"
                + "-iN: number of P pieces\n"
                + "-tN: number of T pieces\n"
                + "-lN: number of L pieces\n"

                + "\n"
                + "Example: TetrisPuzzleSolver.jar -nogui -parallel -grid6x8 -i1 -o5 -t2 -j0 -l1 -s2 -z1"
        );
        System.exit(-1);
    }

    private static void printBoard(int[][] board) {
        for (int y = 0; y < board.length; y++) {
            for (int x = 0; x < board[0].length; x++) {
                System.out.print(board[y][x] + "\t");
            }
            System.out.print("\n");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Integer uiMode = null; //0=cli, 1=gui
        Integer algorithm = null; //0=classic, 1=parallel
        Integer h = null, w = null; //grid size
        Integer p = null, t = null, l = null; //pieces
        boolean firstArg = true;
        if (args.length != 0) {
            for (String arg : args) {
                if (firstArg && arg.startsWith("-LOAD")) {
                    GZIPInputStream in = null;
                    try {
                        in = new GZIPInputStream(new FileInputStream(arg.substring(5)));
                        Pentominos2DSolverMT solver = Pentominos2DSolverMT.loadState(in);
                        Main2D gui = new Main2D();
                        gui.rows.setValue(solver.getHeight());
                        gui.cols.setValue(solver.getWidth());
                        gui.l.setValue(solver.getLBlocks());
                        gui.p.setValue(solver.getPBlocks());
                        gui.t.setValue(solver.getTBlocks());
                        new Visualizer(solver, gui).setVisible(true);
                        return;
                    } catch (Throwable ex) {
                        System.out.println("Can't load state: " + ex);
                        System.exit(2);
                    } finally {
                        try {
                            in.close();
                        } catch (IOException ex) {
                        }
                    }
                } else if (arg.equals("-nogui")) {
                    if (uiMode != null) {
                        printHelp();
                    }
                    uiMode = 0;

                } else if (arg.equals("-gui")) {
                    if (uiMode != null) {
                        printHelp();
                    }
                    uiMode = 1;
                } else if (arg.equals("-classic")) {
                    if (algorithm != null) {
                        printHelp();
                    }
                    algorithm = 0;
                } else if (arg.equals("-parallel")) {
                    if (algorithm != null) {
                        printHelp();
                    }
                    algorithm = 1;
                } else if (arg.startsWith("-grid")) {
                    if (w != null || h != null) {
                        printHelp();
                    }
                    String grid = arg.substring(5);
                    String[] hw = grid.split("x");
                    if (hw.length == 2) {
                        try {
                            h = Integer.parseInt(hw[0]);
                            w = Integer.parseInt(hw[1]);
                            if (h < 1 || w < 1) {
                                printHelp();
                            }
                        } catch (Exception e) {
                            printHelp();
                        }
                    }
                } else if (arg.startsWith("-p")) {
                    if (p != null) {
                        printHelp();
                    }
                    String n = arg.substring(2);
                    try {
                        p = Integer.parseInt(n);
                        if (p < 0) {
                            printHelp();
                        }
                    } catch (Exception e) {
                        printHelp();
                    }
                 }else if (arg.startsWith("-t")) {
                    if (t != null) {
                        printHelp();
                    }
                    String n = arg.substring(2);
                    try {
                        t = Integer.parseInt(n);
                        if (t < 0) {
                            printHelp();
                        }
                    } catch (Exception e) {
                        printHelp();
                    }
                } else if (arg.startsWith("-l")) {
                    if (l != null) {
                        printHelp();
                    }
                    String n = arg.substring(2);
                    try {
                        l = Integer.parseInt(n);
                        if (l < 0) {
                            printHelp();
                        }
                    } catch (Exception e) {
                        printHelp();
                    }
                } else {
                    //invalid parameter
                    printHelp();
                }
                firstArg = false;
            }
            if (uiMode == null) {
                uiMode = 1; //gui by default
            }
            if (algorithm == null) {
                algorithm = 1; //parallel by default
            }
            if (w == null || h == null || p == null || t == null || l == null) { //missing a required parameter
                printHelp();
            }
            if (uiMode == 0) { 
                long lastT = System.nanoTime(), lastIterations = 0;
                System.out.println("Solving...");
				/*
				 * if (algorithm == 0) { //classic algorithm final Pentominos2DSolver solver =
				 * new Pentominos2DSolver(w, h, l, p, t); new Thread() { public void run() {
				 * setPriority(Thread.MAX_PRIORITY); long startT = System.nanoTime(); if
				 * (solver.solve()) { System.out.println("Solved in " + ((System.nanoTime() -
				 * startT) / 1000000L) + " ms"); printBoard(solver.getBoard()); System.exit(0);
				 * } else { System.out.println("Impossible"); System.exit(1); } } }.start(); for
				 * (;;) { try { Thread.sleep(100); } catch (InterruptedException ex) { } long
				 * time = System.nanoTime(); long iters = solver.getIterations();
				 * System.out.println((iters - lastIterations) * (1000000000L / (time - lastT))
				 * + " iterations/s"); lastIterations = iters; lastT = t; } }
				 */
                if (algorithm == 1) { //parallel algorithm
                    final Pentominos2DSolverMT solver = new Pentominos2DSolverMT(w, h, l, p, t);
                    new Thread() {
                        public void run() {
                            setPriority(Thread.MAX_PRIORITY);
                            long startT = System.nanoTime();
                            Solution sol = solver.solve();
                            if (sol != null) {
                                System.out.println("Solved in " + ((System.nanoTime() - startT) / 1000000L) + " ms");
                                printBoard(sol.get());
                                System.exit(0);
                            } else {
                                System.out.println("Impossible");
                                System.exit(1);
                            }
                        }
                    }.start();

                    for (;;) {
                        try {
                            Thread.sleep(100);
                        } catch (InterruptedException ex) {
                        }
                        long time = System.nanoTime();
                        long iters = solver.getIterations();
                        System.out.println((iters - lastIterations) * (1000000000L / (time - lastT)) + " iterations/s");
                        lastIterations = iters;
                        lastT = t;
                    }
                }
            }
            if (uiMode == 1) { 
                if (algorithm == 1) { //parallel algorithm
                    new Visualizer(new Pentominos2DSolverMT(w, h, l, p, t), null).setVisible(true);
                }
            }
        } else {
            //no parameters, show full gui
            new Main2D().setVisible(true);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cols;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    //private javax.swing.JLabel jLabel3;
    //private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    //private javax.swing.JLabel jLabel8;
    //private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JSpinner l;
    private javax.swing.JSpinner p;
    private javax.swing.JSpinner t;
    private javax.swing.JComboBox optimization;
    private javax.swing.JSpinner rows;
    private javax.swing.JButton solve;
    // End of variables declaration//GEN-END:variables
}

